### ISSUE TITLE
查找设备

### ISSUE THREAD

**Issue by AndroidYzk** [EternalNight996/hikvision-rs#1]
// 枚举设备类型，这里我们枚举设备
  let layer_type = MvEnumDeviceLayerType::All;
  // let layer_type =
  //   MV_GIGE_DEVICE | MV_USB_DEVICE | MV_UNKNOWN_DEVICE | MV_1394_DEVICE | MV_CAMERALINK_DEVICE;
  let mut sdk = HC_MVS_CORE_SDK.write().res()?;
  // 创建一个设备列表结构体用于接收枚举结果
  let mut dev_list = MvCcDeviceInfoList::default();

  unsafe {
    // 调用枚举设备函数
    match sdk.enumrate_devices(layer_type, &mut dev_list) {
      CResult::Ok(_) => {
        println!("设备列表设备列表设备列表{:?}", dev_list);
        // 枚举成功，dev_list 现在包含了设备列表
        // 可以遍历dev_list来获取设备信息
      }
      CResult::Err(e) => {
        // 枚举失败，处理错误
        println!("Error enumerating devices: {:?}", e);
      }
    }
  }

您好我这样写查找设备找不到设备，打印出来nDeviceNum是0，能帮忙解答一下嘛

**Comment by EternalNight996** [comment]
/// 这里是一个简单的例子  MvCcDeviceInfoList2是需要自己做处理的
/// 这个库我写的便捷库占资源很小 e-utils = {version = "0.3"}
/// libs/HCMvs/Win64_x64库一定要有否则是连接不上的
async fn enumrate_devices(
  layerType: MvEnumDeviceLayerType,
) {
  let mut out_dev_list = MvCcDeviceInfoList::default();
  let msg = format!("工业摄像头 枚举设备");
  let res = unsafe {
    sdk.enumrate_devices(layerType, &mut out_dev_list)
  };
  let out_dev_list2 = MvCcDeviceInfoList2::from(&mut out_dev_list);
  sdk.set_devlist(out_dev_list);
}

#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
use e_utils::parse::ToStringWithoutNulls as _;
use hikvision::mvs_sdk::{
  constant::INFO_MAX_BUFFER_SIZE,
  types::{MvCcDeviceInfoList, N19MvCCDeviceInfo3Dot0E},
};
use serde::{Deserialize, Serialize};
use std::{
  borrow::Cow,
  ffi::*,
  net::{IpAddr, Ipv4Addr},
};

/// 设备信息    \~english Device info
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct MvCcDeviceInfo2<'a> {
  /// 规范的主要版本
  pub nMajorVer: u16,
  /// 规范的次要版本
  pub nMinorVer: u16,
  /// MAC地址高位
  pub nMacAddrHigh: u32,
  /// MAC地址低位
  pub nMacAddrLow: u32,
  /// 设备传输层协议类型
  pub nTLayerType: u32,
  /// 保留字节
  pub nReserved: [u32; 4],
  /// 特定名
  pub name: Cow<'a, str>,
  /// 不同设备特有信息
  #[serde(flatten)]
  pub SpecialInfo: N19MvCCDeviceInfo3Dot0E2,
}
impl<'a> Default for MvCcDeviceInfo2<'a> {
  fn default() -> Self {
    Self {
      nMajorVer: 0,
      nMinorVer: 0,
      nMacAddrHigh: 0,
      nMacAddrLow: 0,
      nTLayerType: 0,
      nReserved: [0; 4],
      SpecialInfo: N19MvCCDeviceInfo3Dot0E2::stCamLInfo(MvCamLDeviceInfo2::default()),
      name: Cow::default(),
    }
  }
}

/// 不同设备特有信息
#[derive(Debug, Clone, Deserialize, Serialize)]
pub enum N19MvCCDeviceInfo3Dot0E2 {
  stGigEInfo(MvGigeDeviceInfo2),
  stUsb3VInfo(MvUsb3DeviceInfo2),
  stCamLInfo(MvCamLDeviceInfo2),
}

/// CameraLink设备信息
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct MvCamLDeviceInfo2 {
  /// 端口号
  #[serde(with = "hikvision::utils::c_uchar_64_ser")]
  pub chPortID: [u8; INFO_MAX_BUFFER_SIZE],
  /// 设备型号
  #[serde(with = "hikvision::utils::c_uchar_64_ser")]
  pub chModelName: [u8; INFO_MAX_BUFFER_SIZE],
  /// 家族名字
  #[serde(with = "hikvision::utils::c_uchar_64_ser")]
  pub chFamilyName: [u8; INFO_MAX_BUFFER_SIZE],
  /// 设备版本号
  #[serde(with = "hikvision::utils::c_uchar_64_ser")]
  pub chDeviceVersion: [u8; INFO_MAX_BUFFER_SIZE],
  /// 制造商名字
  #[serde(with = "hikvision::utils::c_uchar_64_ser")]
  pub chManufacturerName: [u8; INFO_MAX_BUFFER_SIZE],
  /// 序列号
  #[serde(with = "hikvision::utils::c_uchar_64_ser")]
  pub chSerialNumber: [u8; INFO_MAX_BUFFER_SIZE],
  /// 保留字节
  #[serde(with = "hikvision::utils::c_uint_38_ser")]
  pub nReserved: [c_uint; 38],
}
impl Default for MvCamLDeviceInfo2 {
  fn default() -> Self {
    Self {
      chPortID: [0; INFO_MAX_BUFFER_SIZE],
      chModelName: [0; INFO_MAX_BUFFER_SIZE],
      chFamilyName: [0; INFO_MAX_BUFFER_SIZE],
      chDeviceVersion: [0; INFO_MAX_BUFFER_SIZE],
      chManufacturerName: [0; INFO_MAX_BUFFER_SIZE],
      chSerialNumber: [0; INFO_MAX_BUFFER_SIZE],
      nReserved: [0; 38],
    }
  }
}
/// USB设备信息
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct MvUsb3DeviceInfo2 {
  /// 控制输入端点
  pub CtrlInEndPoint: u8,
  /// 控制输出端点
  pub CtrlOutEndPoint: u8,
  /// 流端点
  pub StreamEndPoint: u8,
  /// 事件端点
  pub EventEndPoint: u8,
  /// 供应商ID号
  pub idVendor: u16,
  /// 产品ID号
  pub idProduct: u16,
  /// 设备序列号
  pub nDeviceNumber: u32,
  /// 设备GUID号
  #[serde(with = "hikvision::utils::c_uchar_64_ser")]
  pub chDeviceGUID: [u8; INFO_MAX_BUFFER_SIZE],
  /// 供应商名字
  #[serde(with = "hikvision::utils::c_uchar_64_ser")]
  pub chVendorName: [u8; INFO_MAX_BUFFER_SIZE],
  /// 型号名字
  #[serde(with = "hikvision::utils::c_uchar_64_ser")]
  pub chModelName: [u8; INFO_MAX_BUFFER_SIZE],
  /// 家族名字
  #[serde(with = "hikvision::utils::c_uchar_64_ser")]
  pub chFamilyName: [u8; INFO_MAX_BUFFER_SIZE],
  /// 设备版本号
  #[serde(with = "hikvision::utils::c_uchar_64_ser")]
  pub chDeviceVersion: [u8; INFO_MAX_BUFFER_SIZE],
  /// 制造商名字
  #[serde(with = "hikvision::utils::c_uchar_64_ser")]
  pub chManufacturerName: [u8; INFO_MAX_BUFFER_SIZE],
  /// 序列号
  #[serde(with = "hikvision::utils::c_uchar_64_ser")]
  pub chSerialNumber: [u8; INFO_MAX_BUFFER_SIZE],
  /// 用户自定义名字
  #[serde(with = "hikvision::utils::c_uchar_64_ser")]
  pub chUserDefinedName: [u8; INFO_MAX_BUFFER_SIZE],
  /// 支持的USB协议
  pub nbcdUSB: u32,
  /// 设备地址
  pub nDeviceAddress: u32,
  /// 保留字节
  pub nReserved: [c_uint; 2],
}
impl Default for MvUsb3DeviceInfo2 {
  fn default() -> Self {
    Self {
      CtrlInEndPoint: 0,
      CtrlOutEndPoint: 0,
      StreamEndPoint: 0,
      EventEndPoint: 0,
      idVendor: 0,
      idProduct: 0,
      nDeviceNumber: 0,
      chDeviceGUID: [0; INFO_MAX_BUFFER_SIZE],
      chVendorName: [0; INFO_MAX_BUFFER_SIZE],
      chModelName: [0; INFO_MAX_BUFFER_SIZE],
      chFamilyName: [0; INFO_MAX_BUFFER_SIZE],
      chDeviceVersion: [0; INFO_MAX_BUFFER_SIZE],
      chManufacturerName: [0; INFO_MAX_BUFFER_SIZE],
      chSerialNumber: [0; INFO_MAX_BUFFER_SIZE],
      chUserDefinedName: [0; INFO_MAX_BUFFER_SIZE],
      nbcdUSB: 0,
      nDeviceAddress: 0,
      nReserved: [0; 2],
    }
  }
}
/// GigE设备信息
#[repr(C)]
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct MvGigeDeviceInfo2 {
  /// IP配置选项
  pub nIpCfgOption: u32,
  /// 当前IP地址配置: bit31-static bit30-dhcp bit29-lla
  pub nIpCfgCurrent: u32,
  /// 当前主机IP地址
  pub nCurrentIp: u32,
  /// 当前子网掩码
  pub nCurrentSubNetMask: u32,
  /// 默认网关
  pub nDefaultGateWay: u32,
  /// 厂商名称
  pub chManufacturerName: [u8; 32],
  /// 型号名称
  pub chModelName: [u8; 32],
  /// 设备固件版本
  pub chDeviceVersion: [u8; 32],
  /// 厂商特殊信息
  #[serde(with = "hikvision::utils::c_uchar_48_ser")]
  pub chManufacturerSpecificInfo: [u8; 48],
  /// 序列号
  pub chSerialNumber: [u8; 16],
  /// 用户定义名称
  pub chUserDefinedName: [u8; 16],
  /// 网口Ip地址
  pub nNetExport: u32,
  /// 保留字节
  pub nReserved: [c_uint; 4],
}
impl Default for MvGigeDeviceInfo2 {
  fn default() -> Self {
    Self {
      nIpCfgOption: 0,
      nIpCfgCurrent: 0,
      nCurrentIp: 0,
      nCurrentSubNetMask: 0,
      nDefaultGateWay: 0,
      chManufacturerName: [0; 32],
      chModelName: [0; 32],
      chDeviceVersion: [0; 32],
      chManufacturerSpecificInfo: [0; 48],
      chSerialNumber: [0; 16],
      chUserDefinedName: [0; 16],
      nNetExport: 0,
      nReserved: [0; 4],
    }
  }
}

/// 设备信息列表    \~english Device Information List
#[repr(C)]
#[derive(Serialize, Deserialize, Default, Clone, Debug)]
pub struct MvCcDeviceInfoList2<'a> {
  /// 在线设备数量
  pub nDeviceNum: u32,
  /// 支持最多256个设备
  pub pDeviceInfo: Vec<MvCcDeviceInfo2<'a>>,
}
impl<'a> From<&mut MvCcDeviceInfoList> for MvCcDeviceInfoList2<'a> {
  fn from(value: &mut MvCcDeviceInfoList) -> Self {
    let pDeviceInfo: Vec<MvCcDeviceInfo2> = value
      .pDeviceInfo
      .iter()
      .enumerate()
      .filter_map(|(i, x)| unsafe {
        (*x).as_ref().map(|x| {
          let special_info;
          let name;
          let addr_fn = |x: u32| -> IpAddr {
            let ip1 = ((x & 0xff000000) >> 24) as u8;
            let ip2 = ((x & 0x00ff0000) >> 16) as u8;
            let ip3 = ((x & 0x0000ff00) >> 8) as u8;
            let ip4 = (x & 0x000000ff) as u8;
            IpAddr::V4(Ipv4Addr::new(ip1, ip2, ip3, ip4))
          };
          #[allow(unused_unsafe)]
          unsafe {
            match &x.SpecialInfo {
              // Match on the GigE device info
              N19MvCCDeviceInfo3Dot0E { stGigEInfo } => {
                special_info = N19MvCCDeviceInfo3Dot0E2::stGigEInfo(MvGigeDeviceInfo2 {
                  nIpCfgOption: stGigEInfo.nIpCfgOption,
                  nIpCfgCurrent: stGigEInfo.nIpCfgCurrent,
                  nCurrentIp: stGigEInfo.nCurrentIp,
                  nCurrentSubNetMask: stGigEInfo.nCurrentSubNetMask,
                  nDefaultGateWay: stGigEInfo.nDefaultGateWay,
                  chManufacturerName: stGigEInfo.chManufacturerName,
                  chModelName: stGigEInfo.chModelName,
                  chDeviceVersion: stGigEInfo.chDeviceVersion,
                  chManufacturerSpecificInfo: stGigEInfo.chManufacturerSpecificInfo,
                  chSerialNumber: stGigEInfo.chSerialNumber,
                  chUserDefinedName: stGigEInfo.chUserDefinedName,
                  nNetExport: stGigEInfo.nNetExport,
                  nReserved: stGigEInfo.nReserved,
                });
                let chUserDefinedName = stGigEInfo.chUserDefinedName.to_string_without_nulls();
                let chModelName = stGigEInfo.chModelName.to_string_without_nulls();
                let dotName = "GigE";
                let address = addr_fn(stGigEInfo.nCurrentIp);
                name =
                  format!("[{i}]{dotName}: {chUserDefinedName} {chModelName} ({address})").into();
              }
              // Match on the USB3 device info
              #[allow(unreachable_patterns)]
              N19MvCCDeviceInfo3Dot0E { stUsb3VInfo } => {
                special_info = N19MvCCDeviceInfo3Dot0E2::stUsb3VInfo(MvUsb3DeviceInfo2 {
                  CtrlInEndPoint: stUsb3VInfo.CtrlInEndPoint,
                  CtrlOutEndPoint: stUsb3VInfo.CtrlOutEndPoint,
                  StreamEndPoint: stUsb3VInfo.StreamEndPoint,
                  EventEndPoint: stUsb3VInfo.EventEndPoint,
                  idVendor: stUsb3VInfo.idVendor,
                  idProduct: stUsb3VInfo.idProduct,
                  nDeviceNumber: stUsb3VInfo.nDeviceNumber,
                  chDeviceGUID: stUsb3VInfo.chDeviceGUID,
                  chVendorName: stUsb3VInfo.chVendorName,
                  chModelName: stUsb3VInfo.chModelName,
                  chFamilyName: stUsb3VInfo.chFamilyName,
                  chDeviceVersion: stUsb3VInfo.chDeviceVersion,
                  chManufacturerName: stUsb3VInfo.chManufacturerName,
                  chSerialNumber: stUsb3VInfo.chSerialNumber,
                  chUserDefinedName: stUsb3VInfo.chUserDefinedName,
                  nbcdUSB: stUsb3VInfo.nbcdUSB,
                  nDeviceAddress: stUsb3VInfo.nDeviceAddress,
                  nReserved: stUsb3VInfo.nReserved,
                });
                let chUserDefinedName = stUsb3VInfo.chUserDefinedName.to_string_without_nulls();
                let chModelName = stUsb3VInfo.chModelName.to_string_without_nulls();
                let dotName = "USB";
                let strSerialNumber = stUsb3VInfo.chSerialNumber.to_string_without_nulls();
                name =
                  format!("[{i}]{dotName}: {chUserDefinedName} {chModelName} ({strSerialNumber})")
                    .into();
              }
              // Match on the CameraLink device info
              #[allow(unreachable_patterns)]
              N19MvCCDeviceInfo3Dot0E { stCamLInfo } => {
                special_info = N19MvCCDeviceInfo3Dot0E2::stCamLInfo(MvCamLDeviceInfo2 {
                  chPortID: stCamLInfo.chPortID,
                  chModelName: stCamLInfo.chModelName,
                  chFamilyName: stCamLInfo.chFamilyName,
                  chDeviceVersion: stCamLInfo.chDeviceVersion,
                  chManufacturerName: stCamLInfo.chManufacturerName,
                  chSerialNumber: stCamLInfo.chSerialNumber,
                  nReserved: stCamLInfo.nReserved,
                });
                let chPortID = stCamLInfo.chPortID.to_string_without_nulls();
                let chModelName = stCamLInfo.chModelName.to_string_without_nulls();
                let dotName = "CameraLink";
                let strSerialNumber = stCamLInfo.chSerialNumber.to_string_without_nulls();
                name =
                  format!("[{i}]{dotName}: {chPortID} {chModelName} ({strSerialNumber})").into();
              }
            }
          };
          MvCcDeviceInfo2 {
            nMajorVer: x.nMajorVer,
            nMinorVer: x.nMinorVer,
            nMacAddrHigh: x.nMacAddrHigh,
            nMacAddrLow: x.nMacAddrLow,
            nTLayerType: x.nTLayerType,
            nReserved: x.nReserved,
            SpecialInfo: special_info,
            name,
          }
        })
      })
      .collect();
    Self {
      nDeviceNum: value.nDeviceNum,
      pDeviceInfo,
    }
  }
}

**Comment by EternalNight996** [comment]
这个库已经用于实际生产，虽然存在一些BUG， 但稳定生产的，如果还有什么不懂可以加我V： eternalnightwechat10
